version: '3.9'

networks:
  mnemosyne_next:
    name: mnemosyne_next
    driver: overlay
    attachable: true

services:
  node:
    image: $DOCKER_IMAGE
    command: >-
      --key $KEY
      --volume /mnemosyne-test-a
      --volume /mnemosyne-test-b
      --login gr.moncrieff@saeon.nrf.ac.za
      --login zd.smith@saeon.nrf.ac.za
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.apps = true
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 5s
    volumes:
      - type: bind
        source: /mnemosyne-test-a
        target: /mnemosyne-test-a
      - type: bind
        source: /mnemosyne-test-b
        target: /mnemosyne-test-b
    ports:
      - 6011:3000
    networks:
      - mnemosyne_next
