remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Mnemosyne
description: HTTP-Range server

# Social media links
social:
  - title: GitHub
    url: https://github.com/SAEON
  - title: Twitter
    url: https://twitter.com/Saeonews

show_downloads: true