version = 0.1
default-task = 'start'

extensions = ['chomp@0.1:prettier']

[[task]]
name = 'start'
env = { TZ='UTC', NODE_ENV='development'}
deps = [ 'src/**/*.js' ]
run = """
node \
  --trace-warnings \
  bin/mnemosyne.js \
    --key TjWnZr4u7w!z%C*F-JaNdRgUkXp2s5v8 \
    --login username \
    --login username2 \
    --volume ./test \
    --volume ./test/mnt1 \
    --volume ./test/mnt2
"""

[[task]]
name = 'lint'
run = "eslint ."


[[task]]
name = 'prettier'
template = 'prettier'
[task.template-options]
ignore-path = '.prettierignore'
files = 'bin/mnemosyne.js package.json src/**/*.@(js|json|yml) ./*.@(js|json|yml|md) ./.github/**/*.@(js|json|yml) ./deploy/**/*.@(js|json|yml)'
loglevel = 'warn'
config = '.prettierrc'

[[task]]
name = 'reset'
run = """
find . \
  -name node_modules \
  -type d \
  -exec rm -rv {} +
find . \
  -name package-lock.json \
  -type f \
  -delete
"""