version = 0.1
default-task = 'start'

extensions = ['chomp@0.1:prettier']

[[task]]
name = 'start'
env = { TZ='UTC', NODE_ENV='development'}
deps = [ 'src/**/*.js' ]
run = """
node \
  --trace-warnings \
  src \
    --key TjWnZr4u7w!z%C*F-JaNdRgUkXp2s5v8 \
    --login zd.smith@saeon.nrf.ac.za \
    --login localhost2 \
    --volume /home/zach/somisana-data \
    --volume /home/zach/temp/somisana-data
"""


[[task]]
name = 'prettier'
template = 'prettier'
[task.template-options]
ignore-path = '.prettierignore'
files = 'src/**/*.@(js|json|yml) ./*.@(js|json|yml|md) ./.github/**/*.@(js|json|yml) ./deploy/**/*.@(js|json|yml)'
loglevel = 'warn'
config = '.prettierrc'

[[task]]
name = 'reset'
run = """
find . \
  -name node_modules \
  -type d \
  -exec rm -rv {} +
find . \
  -name package-lock.json \
  -type f \
  -delete
"""