export { default as httpDelete } from './delete/index.js'
export { default as _404 } from './404/index.js'
export { default as get } from './get/index.js'
export { default as head } from './head/index.js'
export { default as options } from './options/index.js'
export { default as put } from './put/index.js'
export { default as post } from './post/index.js'
