version: '3.9'

networks:
  mnemosyne_stable:
    name: mnemosyne_stable
    driver: overlay
    attachable: true

services:
  node:
    image: $DOCKER_IMAGE
    command: >-
      --key $KEY
      --volume /somisana
      --volume /osgeo
      --login gr.moncrieff@saeon.nrf.ac.za
      --login zd.smith@saeon.nrf.ac.za
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.apps == true
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 5s
      resources:
        limits:
          cpus: "2"
          memory: 250M
    volumes:
      - type: bind
        source: /mnt/somisana/mnemosyne
        target: /somisana
      - type: bind
        source: /mnt/osgeo/mnemosyne
        target: /osgeo
    ports:
      - 7010:3000
    networks:
      - mnemosyne_stable
